apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        author: Katka
        kubernetes.io/change-cause: "Update to green kuard"
    spec:
      containers:
      - name: nginx
        image: nginx