apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-pod
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      failureThreshold: 2
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    readinessProbe:
      httpGet:
        path: /
        port: http
      failureThreshold: 2
