apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: django-app
  name: django-app
spec:
  containers:
  - env:
    - name: DATADIR
      value: /data/db.sqlite3
    command:
    - /bin/sh
    - -c
    - python manage.py migrate; python manage.py runserver 0.0.0.0:8001
    image: misohu/django-school-project:sqlite
    imagePullPolicy: Always
    name: django-app
    ports:
    - containerPort: 8001
    resources: {}
    volumeMounts:
      - name: db-data
        mountPath: /data
  volumes:
    - name: db-data
      hostPath:
        path: /home/pocik/Documents/Tutorials/kubernetes-for-beginners/data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
