apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvx
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: postgres-app
